In [0]:
import numpy as np

In [0]:
X=np.array([[1,1,1,1,1,1],[-1,-1,-1,-1,-1,-1],[1,-1,-1,1,1,1],[1,1,-1,-1,-1,-1]])
Y=np.array([[1,1,1],[-1,-1,-1],[-1,1,1],[1,-1,1]])

In [54]:
X

array([[ 1,  1,  1,  1,  1,  1],
       [-1, -1, -1, -1, -1, -1],
       [ 1, -1, -1,  1,  1,  1],
       [ 1,  1, -1, -1, -1, -1]])

In [55]:
Y

array([[ 1,  1,  1],
       [-1, -1, -1],
       [-1,  1,  1],
       [ 1, -1,  1]])

In [0]:
weightMatrix=np.zeros((6,3)).astype(int)

In [0]:
for i in range(X.shape[0]):
  weightMatrix+=np.dot( (X[i].reshape(1,X[i].shape[0])).T , Y[i].reshape(1,Y[i].shape[0]) )

In [58]:
weightMatrix

array([[2, 2, 4],
       [4, 0, 2],
       [2, 2, 0],
       [0, 4, 2],
       [0, 4, 2],
       [0, 4, 2]])

In [0]:
def activation(val):
  if val>=0:
    return 1
  else:
    return -1;

In [0]:
#Here we take Y as input and obtain X values
def testForY(X,weightMatrix,Y):
  obtainedY=np.zeros((4,3))
  obtainedY=obtainedY.astype(int)
  for i in range(4):
    obtainedY[i]=(np.dot( (X[i].reshape(1,X[i].shape[0])) , (weightMatrix)) )

  for i in range(len(obtainedY)):
    for j in range(len(obtainedY[i])):
      obtainedY[i][j]=activation(obtainedY[i][j])
  print('obtainedY :-',obtainedY)
  
#Here we take Y as input and obtain X values
def testForX(X,weightMatrix,Y):
  obtainedX=np.zeros((4,6))
  obtainedX=obtainedX.astype(int)
  for i in range(4):
    obtainedX[i]=(np.dot( (Y[i].reshape(1,Y[i].shape[0])) , (weightMatrix).T) )

  for i in range(len(obtainedX)):
    for j in range(len(obtainedX[i])):
      obtainedX[i][j]=activation(obtainedX[i][j])
  print('obtainedX :-',obtainedX)

In [75]:
testForY(X,weightMatrix,Y)

obtainedY :- [[ 1  1  1]
 [-1 -1 -1]
 [-1  1  1]
 [ 1 -1  1]]


In [76]:
testForX(X,weightMatrix,Y)

obtainedX :- [[ 1  1  1  1  1  1]
 [-1 -1 -1 -1 -1 -1]
 [ 1 -1  1  1  1  1]
 [ 1  1  1 -1 -1 -1]]


Here we see that, in the obtainedX matrix two of the values differ from the original X matrix. This problem occurs due to **incorrect convergence of BAM**. So, we observe that BAM might not always produce the closest associtation.
